language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm --prefix website start
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: website/build/pwa-gh-pages
  on:
    branch: master